spring:
  application:
    name: application-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/account/**
      discovery:
        locator:
          enabled: true

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


